### ISSUE TITLE
Nutrition stats

### ISSUE THREAD

**Issue by muety** [kronos-et-al/MensaApp#124]
The app looks amazing, thanks a lot! As an additional feature, it would be super cool to also see nutrition stats for each meal, see [here](https://github.com/muety/kit-mensa-scraper/tree/master/archive).

**Comment by worldofjoni** [comment]
Thanks! We considered adding nutritinal information but decided not to because in our experience they semed not that realistic/accurate and thus not worth our time. If anyone would like to implement that though it would be a nice addition and should be not to hard to add.

**Comment by uglrl** [comment]
The trawling aspect is now implemented. The database, graphql and app still need to be changed.

**Comment by worldofjoni** [comment]
@uglrl nice, do you want to create a pull request?

**Comment by uglrl** [comment]
No, because the database etc. still has to be implemented. And the trawling still has some bugs

**Comment by muety** [comment]
Would love to have this included! @uglrl if you manage to finish up the data scraping (you might take inspiration from [here](https://github.com/muety/kit-mensa-scraper/blob/a596d037998cb49d513c7e97f376eac8fe8f36c7/lib/src/main/java/edu/kit/aifb/atks/mensascraper/lib/KITMensaScraper.java#L149)) (and possibly also adapt the database schema), I'll probably give it a go and try my hand at the GraphQL API and app integration.

**Comment by worldofjoni** [comment]
Great that you want to contribute! 😄 

I think the following things would be neccesarry to get this going:
Backend:
- [ ] Web scraping: looks like its already implemented by @uglrl , just needs to be reviewed/merged
- [ ] Database schema update incl. access component in backend: I think I @worldofjoni can take a look at that
- [ ]  Changes to the Graphql api. That should not be too much work and a task to get familiar with the project @muety

Frontend:
- [ ] GraphQL-CLient part
- [ ] Internal shananigans like storage to the database for offline use etc. I am not an expert at this part. Maybe @AlexKutschera can help here?
- [ ] Addition to the UI

---
Here are some excerpts of our internal documentation (which we should incoperate into this repository at some point).
## Backend
a bit outdated (especially the image-management part) but the components relevant to us now should still be correct: GraphQL and Database
![image](https://github.com/kronos-et-al/MensaApp/assets/47496388/1f695fd9-2db5-4ad6-851e-64d0ce351ea4)

## Frontend
this might also be dated but nevertheless
![image](https://github.com/kronos-et-al/MensaApp/assets/47496388/3080504b-82da-4c31-9069-0a1a9df2bf5a)

# Further proceedings
I think we can assemble this directly on the backend branch.
@uglrl you might create a pr of your scraping part so I can take a look at it

---
@muety if anything is unclear or you have any further questions feel free to ask

**Comment by worldofjoni** [comment]
Here are some excerpts of our internal documentation (which we should incoperate into this repository at some point).
## Backend
a bit outdated (especially the image-management part) but the components relevant to us now should still be correct: GraphQL and Database
![image](https://github.com/kronos-et-al/MensaApp/assets/47496388/1f695fd9-2db5-4ad6-851e-64d0ce351ea4)

## Frontend
this might also be dated but nevertheless
![image](https://github.com/kronos-et-al/MensaApp/assets/47496388/3080504b-82da-4c31-9069-0a1a9df2bf5a)

**Comment by muety** [comment]
Awesome, very helpful! I'll start implementing API and app once you guys tell me the scraping- and database parts are done.

**Comment by muety** [comment]
Any news on this? :)

**Comment by worldofjoni** [comment]
Actually, yes!
The backend part is effectively done (the graphql changes were really not much work and natural to do with the rest together), meaning they are just waiting to get merged (#133  #128), this should get done in the next view days. 
All for the frontend relevant parts (namely the graphql API changes) are already available in `nutrition_data`. So you could start with your work on the frontend part. A current copy of the updated API schema can also be found in the thread of #128.

**Comment by muety** [comment]
Awesome news, thanks for that :raised_hands: Will give it a go probably on the weekend.

**Comment by muety** [comment]
Quick update on my end: I managed to get everything set up locally and was able to implement UI for showing nutrition data on the app (inside the accordion, next to additives, etc.). Still need to adapt the database schema and persist nutrition information to the app database. 

Would be cool to get #133 merged soon, so I can work from a clean branch (had to do some small ad-hoc fixes to get the app compile since backend and frontend seem to have diverged a bit).

**Comment by worldofjoni** [comment]
#128 was only one half...

**Comment by muety** [comment]
I think this was pretty much completed with #147 and #157, no? Any predictions on when a new version will be released actually?

**Comment by AlexKutschera** [comment]
Released on both Android and iOS today
