### ISSUE TITLE
Geflügel aus dem Gerichtsnamen erkennen

### ISSUE THREAD

**Issue by AlexKutschera** [kronos-et-al/MensaApp#129]
**Is your feature request related to a problem? Please describe.**
Gerichte welche Hühnerfleisch enthalten werden von der Mensa nicht gekennzeichnet, entsprechend muss den Titel lesen um zu wissen ob das Gericht vegetarisch ist oder nicht.

**Describe the solution you'd like**
Erkennung eines neuen Gerichtstypen Geflügel über folgenden Regex
`/(Geflügel|H(ü|ä|u|a)hn)/gmi`

**Describe alternatives you've considered**
Der Mensa eine traurige Mail schreiben ob sie das nicht selbst angeben können:(

**Additional context**
Vor der Implementierung wäre es sinnvoll eine Regex Datenbank abfrage durchzuführen um zu prüfen ob der vorgeschlagene Regex False/Positives auslöst. Wenn in der bestehenden Datenbank keine False/Positivs auftreten kann der Regex als zuverlässig betrachtet werden

**Comment by uglrl** [comment]
Man könnte auch noch Pute hinzufügen

**Comment by uglrl** [comment]
Someone needs to check the database. I don't have access to it.

**Comment by worldofjoni** [comment]
Not quite (reopened pr)
