### ISSUE TITLE
Linie 4 fehlt?

### ISSUE THREAD

**Issue by JuliusJacobitz** [kronos-et-al/MensaApp#130]
**Describe the bug**
Seit dieser Woche fehlt die Linie 4 (Gnocchi) in der Übersicht. 

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 13
 - Browser stock
 - Version 1.0.4

**Comment by worldofjoni** [comment]
Hallo,
Bei mir wird Linie 4 erwartungsgemäß angezeigt. Allerdings veröffentlicht die Mensa die Speisepläne für Linie 4 oft erst sehr spät, teilweise erst im Laufe des Vormittags während der Mensa-Öffnungszeit. Wir aktualisieren unsere Daten (am Vormittag) zu jeder vollen Viertelstunde. Somit sollten die Gerichte spätestens 15min nachdem sie auf der Webseite sichtbar sind angezeigt werden.

Falls du der Meinung bist, es besteht darüber hinaus ein Problem kannst du den Issue gerne wieder öffnen.
