### ISSUE TITLE
Android Adaptive Icon

### ISSUE THREAD

**Issue by SeineEloquenz** [kronos-et-al/MensaApp#134]
**Is your feature request related to a problem? Please describe.**
The App does not follow the system theming when using Themed Icons.

**Describe the solution you'd like**
Support for [Android Adaptive Icons](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive)

**Describe alternatives you've considered**
This is the standard way that should be followed to support themed icons.

**Additional context**
To support the feature, it should be sufficient to add a monochrome icon tag in `app/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml`

**Comment by worldofjoni** [comment]
@AlexKutschera ?
