### ISSUE TITLE
API returns `null` nutrition data for sides

### ISSUE THREAD

**Issue by muety** [kronos-et-al/MensaApp#146]
Example query (latest backend version):

```graphql
{
  getCanteen(canteenId: "5fe2cd62-52f7-4686-bd3a-88c0588d9874") {
    id
    name
    lines {
      name
      meals(date: "2024-03-25") {
        id
        name
        nutritionData {
          energy
        }
        sides {
          id
          name
          nutritionData {
            energy
          }
        }
      }
    }
  }
}
```

Even though nutrition data is present, e.g. for the Himbeerquark:

![image](https://github.com/kronos-et-al/MensaApp/assets/8978843/da43109f-f086-45e7-826d-e21c1fac4b95)

**Comment by worldofjoni** [comment]
@uglrl ?

**Comment by uglrl** [comment]
I could not verify this. It seems (based on current data) that this is fixed. If the issue comes up again, please include the raw html file for verification.

**Comment by worldofjoni** [comment]
I had in mind that nutrients are not parsed for sides yet. if that is not the case, then this is strange in fact.

**Comment by AlexKutschera** [comment]
as of now i don't see any missing data. For the sample query above it seems that the data just has not been parsed for meals as well as sides back then
