### ISSUE TITLE
Android workflow: Tests timeout

### ISSUE THREAD

**Issue by uglrl** [kronos-et-al/MensaApp#152]
**Describe the bug**
All tests exept dateformat recieve a timeout

**To Reproduce**
Look at the actions in github

**Expected behavior**
The tests work

**Screenshots**
![image](https://github.com/kronos-et-al/MensaApp/assets/134957879/87e136b1-dd1a-4c8d-aa1e-e213fa05d41e)

**Comment by uglrl** [comment]
When will this be fixed?

**Comment by uglrl** [comment]
Would it perhaps be possible to run the demo backend on github and start it automatically with an action, since it is only used for testing purposes?

**Comment by AlexKutschera** [comment]
fixed

**Comment by AlexKutschera** [comment]
fixed
