### ISSUE TITLE
Inconsistent report barrier: off by one

### ISSUE THREAD

**Issue by worldofjoni** [kronos-et-al/MensaApp#159]
The report mail template mentions, that X reports are needed for an image to be hidden automatically, but actually, X + 1 are necessary.

Report barrier:
https://github.com/kronos-et-al/MensaApp/blob/43cccc038a4cc48df39b59311fdc10ecd57f245f/backend/src/layer/logic/api_command/command_handler.rs#L68C35-L68C36

Mail template:
https://github.com/kronos-et-al/MensaApp/blob/43cccc038a4cc48df39b59311fdc10ecd57f245f/backend/src/layer/data/mail/template.txt#L6C51-L6C69

**Comment by uglrl** [comment]
This looks to be fixed, seeing as there is now a >= instead of a > in the will_be_hidden function.
